var protagonista = [
    "Az (Maga de Tróia)",
    "Zarco (Mágico de Carrossel)",
    "Leoyuko (Mago da Luz/Herdeiro das Prisões)",
    "Céu (Mago Flecha)",
    "Asturia (Alma Primordial)",
    "Liza Mor (Maga de Ferro)",
    "Nashi (Mago da Primavera)",
    "Késia (amuleto do azar)",
    "Antares (Estrela de escorpião)",
    "Neris Nereu (Mago Absoluto)",
    "Momo Salém (Mago do Sangue)",
    "Klóris Clorfi (Maga Verde)",
    "Meraki (Maga da Alma)",
    "Akashi (Maga Cadente)",
    "Anil (Asa de Mariposa)",
    "Moira (Maga Aviadora)",
    "Zari Iraz (mago ampulheta)",
    "Lubela (Maga de Fortal)",
    "Ignes Nalu (Maga Faísca)",
    "Ácir (o último Mago das Cinzas)",
    "Nix (Maga da Noite)",
    "Anis Enyo (Maga Ametista)",
    "Zarco",
    "Nix",
    "Morfeu",
    "Violeta Enyo",
    "Irús",
    "Ásra Nuit (Maga de Ouro)",
    "Hari de Alcali (Mago do Sal)",
    "Zinka-ka (Mago dos Fios)",
    "Centauri Irua"
];

var protagonista2 = [
  "Az (Maga de Tróia)",
  "Zarco (Mágico de Carrossel)",
  "Leoyuko (Mago da Luz/Herdeiro das Prisões)",
  "Céu (Mago Flecha)",
  "Asturia (Alma Primordial)",
  "Liza Mor (Maga de Ferro)",
  "Nashi (Mago da Primavera)",
  "Késia (amuleto do azar)",
  "Antares (Estrela de escorpião)",
  "Neris Nereu (Mago Absoluto)",
  "Momo Salém (Mago do Sangue)",
  "Klóris Clorfi (Maga Verde)",
  "Meraki (Maga da Alma)",
  "Akashi (Maga Cadente)",
  "Anil (Asa de Mariposa)",
  "Moira (Maga Aviadora)",
  "Zari Iraz (mago ampulheta)",
  "Lubela (Maga de Fortal)",
  "Ignes Nalu (Maga Faísca)",
  "Ácir (o último Mago das Cinzas)",
  "Nix (Maga da Noite)",
  "Anis Enyo (Maga Ametista)",
  "Zarco",
  "Nix",
  "Morfeu",
  "Violeta Enyo",
  "Irús",
  "Ásra Nuit (Maga de Ouro)",
  "Hari de Alcali (Mago do Sal)",
  "Zinka-ka (Mago dos Fios)",
  "Centauri Irua"
];

var plot = [
    "viagem no tempo",
    "Mago vs Mago",
    "Mago desaparecido",
    "Guardião",
    "Missão Muito Pouco Importante",
    "Visitando aquele reino estranho",
    "Turistando",
    "Apredendo Algo Casual",
    "Capa!",
    "Criando inimigos no reino amigo e amigo no reino inimigo",
    "Música e arte",
    "Cozinhando com você",
    "Ametistas de Repente",
    "Luz, sombra!",
    "Dança comigo?",
    "Flor da Meia noite",
    "Correio de amor mágico",
    "Investigando um Mago ~de maneira trivial",
    "A Sociedade dos Magos Secreta",
    "Mago Sazonal",
    "A Magia Proibida",
    "Fantasma de Inverno",
    "Na Aula de História",
    "Viagem de um Dirigivel Mágico",
    "Boyband",
    "Girlband",
    "Magicband",
    "Torneio Mágico",
    "Reunião de Magos",
    "Conselho de Mago",
    "Encontro entre reinos",
    "MAGO SURPRESA!!!",
    "Recebendo ajuda de outro mago",
    "Mago Sino",
    "Mago-chefe (Mestre de Az)",
    "Gina (Maga Chave)",
    "Mago Explosivo",
    "Rei (Monarca)",
    "Senhora Joshura (mãe de Leo)",
    "Lírio (animal)",
    "Mago do Navio (Capitão)",
    "Pirata (Pai de Liza Mor)",
    "Secretário",
    "Soldados-magos",
    "Nari (Irmã de Neris, Maga da Formação)",
    "Nereti (Pai de Nereu)",
    "Mago Vagante (Um alquimista)",
    "Cidra",
    "Maga Capitã (líder do reino de São Castelo)",
    "Senhora (Maga Raio)",
    "Senhor Carlos (Guarda dos portões da casa de Lubela)",
    "5 guarda-costas",
    "Sacerdote da Terra",
    "Cavaleira",
    "Soldado (Responsável de Hari)",
    "Magos Dourados",
    "Senhora Carmine (Maga das Runas)",
    "Mago das Chamas Azul",
    "Sacerdotisa do Sol",
    "Astrais",
    "Mago da Corte (Representante da Roda em todos os reinos)",
    "Dariela (Prefeita do reino)",
    "Capitã (Avó de Az)",
    "Sirena (Governante Anciã)",
    "Aster (Cuidadora de Asturia)",
    "Quikeo",
    "Magos da Formação (Residem na Capital, sua mãe é a líder)",
    "Ouriço (Líder, incomunicável)",
    "Zila (Guardiã do Bosque Cinza - Floresta, maga das cinzas)",
    "Sacerdote do Tempo",
    "Mago da Lâmina Cor de Rosa",
    "Aruko (animal da espécie “rato”)",
    "Osíris (Criador de Raios, Líder)",
    "Maga de Coração Azul (Maga do inverno)",
    "Selki (Mago da Destruição)",
    "Guido (Mago da Tempestade)",
    "Kaivi (Maga Caçadora, mãe de Momo)",
    "Kal (Tia de Nashi e Késia)",
    "Mestre Zah (Mago do Teletransporte)",
    "Surfina (Aprendiz de Klóris)",
    "Ram (Mago Fantasma)",
    "Kendra (Artesã das Capas)",
    "Magnésio (Mago Mercador)",
    "Physalia (Mestre das Espadas)",
    "Orianna (Maga da Purificação)",
    "Mago de Vidro",
    "Áurea de Alcali",
    "Alto Mago",
    "Joalino Onilajo",
    "Azamira (Maga dos Brinquedos)",
    "Ciano (Mago das Portas)",
    "Sacerdotisa do Azar",
    "Sombra",
    "escola",
    "amnésia",
    "assassinato",
    "guerra",
    "opostos",
    "diário",
    "a profecia",
    "o escolhido",
    "clãs inimigos",
    "um reino na ruína",
    "superação",
    "clichê invertido",
    "uma fuga",
    "jornada de vilão",
    "jornada de herói",
    "vingança",
    "amor proibido",
    "conflito familiar",
    "herdeiro perdido",
    "artefato mágico",
    "abrir portal",
    "o que é amor?",
    "amigos de infância",
    "maldição",
    "rivalidade",
    "vidas passadas",
    "magia",
    "traição",
    "usurpação",
    "troca de identidade",
    "piratas",
    "uma vida eterna",
    "conto de fada",
    "clube vs clube",
    "meninas vs meninos",
    "triângulo amoroso",
    "troca de corpo",
    "ler mentes",
    "famílias rivais",
    "ajudando o cupido",
    "viagem ao mundo",
    "casamento arranjado",
    "chantagem",
    "troca de corpo",
    "lovers to enemies",
    "guerra",
    "resgate",
    "inimigos de infância",
    "amigos de infância",
    "salvar o mundo",
    "visitando o inferno",
    "concurso",
    "baile fantasia",
    "acampamento!",
    "magias opostas",
    "escolha do mago do reino",
    "infância",
    "criatura-mágica fofamente perigosa",
    "batalha",
    "troca de mago e guardião",
    "à você, dedico essa carta ",
    "primeira vez usando magia????",
    "magia é física, vórtice é matemática, o que nos resta é química",
    "ruínas",
    "prisão injusta!!!!",
    "Sua casa",
    "O mais forte",
    "Mestre e Aprendiz",
    "Dancinha terrivelmente vergonhosa",
    "Um dia sem magia"
    ];

var estilo = [
  "Capital",
  "Cidade Saturno",
  "Terra das Montanhas",
  "Mar Ciano",
  "Nação do Céu",
  "Carrossel",
  "Coki-Mélio",
  "Fortaleza",
  "Pico Magdalene",
  "Reino Dourado",
  "Céu Carmim",
  "São Castelo",
  "Floresta Magenta",
  "Átrio",
  "Túmulos de Escorpiões",
  "Água-morta",
  "Além",
      "Baile da Roda",
      "Baile da Roda",
      "Baile da Roda",
      "Baile da Roda",
      "Baile da Roda",
      "Salão da Essência (Testes de magias)",
      "Corte da Capital (Centauri’Irua está aqui)",
      "Festival dos Destinos",
      "Portão Cristal (Barreira de Coki-mélio-mar ciano)",
      "Floresta de Cogumelos",
      "Campos de flores (Violeta gosta desse lugar)",
      "Portão quebrado de Coki-mélio",
      "Aldeia Auris (Anis mora aqui)",
      "Biblioteca de Fortal (a maior)",
      "Castelo Máscara",
      "Subúrbios de São Castelo",
      "Loja de Capas Magas (Ignes)",
      "Bosque Cinza (Onde Ácir vive)",
      "Barreira Vermelha (Átrio-terra das montanhas)",
      "Grande Escola Castelo",
      "Pilares da Criação",
      "Mercado Saturno",
      "Vilarejo de Floresta Magenta",
      "Ilhas de Refúgio (Onde Momo vivia)",
      "Maior Pico (vulcão)",
      "Festival Yamore",
      "Festival das Fadas",
      "Montanha de Nashi",
      "Prisão do Cordão",
      "Prisão Circular",
      "Cúpula Domo",
      "Central de Carrossel (Onde Az fica)",
      "Templo de Água-morta",
      "Torre Céu (Anil e Moira moram por aqui)",
      "Feira-voadora"
  ];

var genero = [
      "romance",
      "mistério",
      "fantasia",
      "ficção adolescente",
      "suspense",
      "ação",
      "aventura",
      "drama",
      "horror",
      "thriller psicológico",
      "comédia",
      "policial",
      "conto de fadas",
      "jovem adulto",
      "histórico",
      ];

      
function formarFrase() {
  var sorteioProtagonista = protagonista[Math.floor(Math.random() * protagonista.length)];
  var sorteioProtagonista2 = protagonista2[Math.floor(Math.random() * protagonista2.length)];
  var sorteioPlot = plot[Math.floor(Math.random() * plot.length)];
  var sorteioEstilo = estilo[Math.floor(Math.random() * estilo.length)];
  var sorteioGenero = genero[Math.floor(Math.random() * genero.length)];

  var fraseCompleta = "꒰ᐢ. .ᐢ꒱₊˚⊹ Eu vou escrever uma história do gênero " + sorteioGenero + " que envolve " +"'" + sorteioPlot  +"'" +  ". \nCom os personagens: " + sorteioProtagonista + " e " + sorteioProtagonista2 + ". \n O ambiente será " + "'" + sorteioEstilo + "'.˙ ̟🐇 !!";
document.getElementById("fraseCompleta").textContent = fraseCompleta;
}



function copiarFrase() {
  var fraseCompleta = document.getElementById("fraseCompleta").textContent;
  navigator.clipboard.writeText(fraseCompleta).then(function() {
    alert("──★ A frase foi copiada com sucesso!");
  },  function() {
    alert("Não foi possível copiar a frase.");
  });
}
function refazerSorteio() {
}

